### ISSUE TITLE
inquiry about the NLI paper

### ISSUE THREAD

**Issue by hjian42** [yunitata/continuous-n-gram-AA#1]
Hi Yunita,

I read your NLI paper. It was a great work.
Have you tried to use word and char embeddings for the NLI task. I wonder whether that could also boost the score for that task?

Hang

**Comment by yunitata** [comment]
Hi Hang, 
Thanks for reading our paper.  We have not try the combinations of word and char embedding for NLI, since the results on our authorship attribution task did not seem encouraging. Results from the experiment using only word embedding also obtained lower performance than char embedding. We think that word features are not effective for NLI task which commonly has predefined topics (for both essay and speech).

**Comment by hjian42** [comment]
Hi Yunita,

Thank you for the observations! This is very helpful.
